# shoutout to this legend https://github.com/utilitywarehouse/onboarding-gquinelato/blob/master/.circleci/config.yml
workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          context: onboarding

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: docker login -u onboarding -p $UW_DOCKER_PASS registry.uw.systems
      - run:
          name: Docker build
          command: |
            docker build -t registry.uw.systems/onboarding/onboarding-exercise-ed-putans:$CIRCLE_SHA1 -t registry.uw.systems/onboarding/onboarding-exercise-ed-putans:latest .
      - run:
          name: Docker push
          command: docker push registry.uw.systems/onboarding/onboarding-exercise-ed-putans
