version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn
  test:
    docker:
      - image: circleci/node:12.9.1-browsers
      - run: yarn test
