version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_laygier_caching: true
      - run: echo $UW_DOCKER_PASS
      - run: docker login -u onboarding -p $UW_DOCKER_PASS registry.uw.systems
      - run: docker build -t registry.uw.systems/onboarding/onboarding-exercise-ed-putans:$CIRCLE_SHA1 -t registry.uw.systems/onboarding/onboarding-exercise-ed-putans:latest .
      - run: docker push registry.uw.systems/onboarding/onboarding-exercise-ed-putans
            
workflows:
    build:
      jobs:
        - build
    deploy:
      jobs:
        - deploy